### ISSUE TITLE
【问题请教】

### ISSUE THREAD

**Issue by zyzisyz** [eddielyc/pr_BUPT#1]
Hi，同学，非常感谢你能分享你的代码和解题思路。

但看了感觉你的代码后，我有一些疑惑，想要请教一下你。
在你的代码中，你可以使用LBP特征提取 或 调用别人的Alexmodel模型提取特征 两种方法，默认训练10次，但似乎每次的特征提取都没有利用到上一次网络训练的结果，因此我认为，代码中每一次提取的特征都是一样的。

所以我觉得experiment这个函数调用一次就可以了，有点疑惑为什么想要调用10次取平均值呢？

**Comment by eddielyc** [comment]
10次取平均主要是K-means++里初始点会影响最后的结果，一般只是略有波动所以取一下平均。至于为什么把整个实验跑10遍，那只是省事，其实可以把跑这个循环放到experiment函数里K-means聚类的那部分:grin:

**Comment by zyzisyz** [comment]
> 10次取平均主要是K-means++里初始点会影响最后的结果，一般只是略有波动所以取一下平均。至于为什么把整个实验跑10遍，那只是省事，其实可以把跑这个循环放到experiment函数里K-means聚类的那部分😁

好的，写写大佬的解答~~~
